### ISSUE TITLE
@deprecated annotations prevent @Counted (and maybe other annotations) working

### ISSUE THREAD

**Issue by nicktindall** [ryantenney/metrics-spring#101]
When a method has either
* the java.lang.Deprecated annotation
* @deprecated included in its JavaDoc

it prevents @Counted (and possibly other annotations) working, with the error message:
`Ignoring @Counted on method com.x.y.z.SomeService.doSomething due to illegal modifiers: `

**Comment by nicktindall** [comment]
Actually its more complicated than that. More information pending.

**Comment by nicktindall** [comment]
Will re-raise if I can make a unit test that breaks. I think it could be interactions between post-processors in our Spring config.

**Comment by nicktindall** [comment]
I've noticed a scenario, I'm not sure what causes it, where Method.getModifiers() returns the value 131073 (=10 0000 0000 0000 0001). Which breaks the logic in `com.ryantenney.metrics.spring.AnnotationFilter`:

```
private boolean checkModifiers(Member member, int allowed) {
	int modifiers = member.getModifiers();
	return (modifiers & allowed) == modifiers;
}
```
Its the presence of either of the deprecated annotations that seems to trigger it. It might be more robust if AnnotationFilter applied a mask for the relevant bits only (the 12 least significant bits I think). I don't have a deep enough understanding of what the AnnotationFilter is about though, so maybe this is by design?

**Comment by ryantenney** [comment]
That is not by design and I very much like the idea of masking the relevant bits, I'll get to this shortly. Thanks!

**Comment by nicktindall** [comment]
No thank you :)

**Comment by ryantenney** [comment]
What version of the compiler and JVM are you using?  With JVM 8 I'm not seeing a deprecated modifier.

**Comment by nicktindall** [comment]
I'm working with Oracle JVM 7, but I've only seen it happen under certain
circumstances (in certain parts of our app), I haven't been able to build a
simple reproduction of the issue. The only thing I can think that might be
causing it is if there were a proxy class (cglib or something) that was
being queried instead of the actual class that the annotation was on. But
this is just a guess. I tried debugging it but a lot of that reflection
code didn't seem to be debug-able.

I could keep digging to try and get to the bottom of the issue, if I get a
chance I'll make an example. I'm curious as to how its happening myself.

The language spec doesn't mention anything about a deprecated modifier. I
feel like this is a result of a bug in something else.

Nick Tindall
0413 177 761

**Comment by ryantenney** [comment]
Have been unable to replicate. Feel free to reopen if this is still an outstanding issue, or to anyone else who might experience this issue, comment on this issue.
