### ISSUE TITLE
(documentation?) readme.md example on xml config vs xsd

### ISSUE THREAD

**Issue by mcampbell** [ryantenney/metrics-spring#104]
The docs mention
` <metrics:reporter type="console" metric-registry="metrics" period="1m" />`

but the xsd has no "period" attribute in the `reporter` attribute, causing intellij to frown.  

Am I misunderstanding this?

**Comment by ryantenney** [comment]
Since a reporter may define an arbitrary set of attributes, `metrics:reporter` cannot enumerate them all and instead specifies `xsd:anyAttribute`.  Both Eclipse and Spring process it without any complaints.  If a change is needed to fully support IntelliJ I'd be open to it.

**Comment by mcampbell** [comment]
I see, thanks.  I'm not sure it's a big deal, since it does seem to work ok, but wondered if I was misunderstanding something or it was an actual issue.  It seems the former =)
