### ISSUE TITLE
Where to put the @EnableMetrics?

### ISSUE THREAD

**Issue by cooniur** [ryantenney/metrics-spring#105]
I use Java code based Spring configruation.

If I put @EnableMetrics at AppConfig class, my methods annotated with @Timed in Spring @Controller cannot be discovered.

If I put @EnableMetrics at WebMvcConfig class, my methods annotated with @Timed in the service layer cannot be discovered.

If I put @EnabledMetrics at both of the classes, I get InstanceAlreadyExistsException when starting JmxReporter.

What can I do to make my @Timed methods in @Controller discovered?

**Comment by ryantenney** [comment]
Did you find a solution?  I haven't encountered this situation previously.

**Comment by cvanslyke** [comment]
I am having this same exact issue. I can add @Timed annotations to non-Controller methods and everything works as expected, but if I add the annotation to a @Controller method my controller is not discovered.

**Comment by ryantenney** [comment]
Does your controller class implement any interfaces? If so, Spring AOP attempts to use a Java proxy, instead of a CGLIB Proxy, which would cause problems on your controller. The solution would be to eliminate the interface, or to set the attribute proxyTargetClass=true in the @EnableMetrics annotation.

**Comment by cvanslyke** [comment]
Wow, fast response. No it does not... I'm doing something like this:

    @Controller
    public class LinkedDataController {
    .
    .
    .
    @RequestMapping(
        value="/search",
        method=RequestMethod.GET, 
        produces=MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    @Timed
    public ResponseEntity<String> search(...) {

**Comment by cvanslyke** [comment]
Funny, I tried adding proxyTargetClass to my @EnableMetrics annotation and it seemed to resolve the problem.

**Comment by cvanslyke** [comment]
I tried what you suggested anyway, and it seemed to resolve the problem.

**Comment by ryantenney** [comment]
Glad to hear it!

**Comment by phantom-1** [comment]
I am unclear: was the solution to add EnableMetrics(proxyTargetClass=true) to BOTH your AppConfig and WebMVCConfig? I am faced with the same issue.

**Comment by cooniur** [comment]
@phantom-1 Yes, I have to add `@EnableMetrics(proxyTargetClass = true)` to BOTH the `AppConfig` and `WebMVCConfig`. Also, I have to add `@EnableAspectJAutoProxy(proxyTargetClass = true)` to BOTH of them.
