### ISSUE TITLE
Enable configuration of graphite

### ISSUE THREAD

**Issue by davidkarlsen** [ryantenney/metrics-spring#106]
When using http://www.ryantenney.com/metrics-spring/:
<metrics:reporter type="graphite" metric-registry="metricsRegistry" enabled="true" period="1m" />

how am I able to configure the graphite server endpoint (ip/port) as in:
https://dropwizard.github.io/metrics/3.1.0/manual/graphite/

?

**Comment by ryantenney** [comment]
Here's an example of how to configure the graphite reporter using Spring XML:

```xml
<metrics:reporter
    id="graphite"
    metric-registry="metrics"
    type="graphite"
    host="localhost"
    port="6666"
    period="1s"
    rate-unit="SECONDS"
    duration-unit="MILLISECONDS" />
```
