### ISSUE TITLE
configureReporters() not being called.

### ISSUE THREAD

**Issue by zkendall** [ryantenney/metrics-spring#107]
I have implemented MetricsConfigurerAdapter, but configureReporters() isn't called unless I manually call it myself, such as from within getMetricRegistry().

Update: I figured out that it is because I had my getMetricRegistry() method, labeled as a bean. It should be documented that the library clients should not define their own bean, because DelegatingMetricsConfiguration provides it for you and handles the configuring based on your overridden methods.

Update2: Perhaps the main conflict was injecting a MetricRegistry field into my config class.

**Comment by Aloren** [comment]
@zkendall 
I suppose, that this is a bug: providing my own metric registry in MetricsConfigurerAdapter should work. Currently this value is ignored.
@ryantenney please, help us find out how MetricsConfigurerAdapter is supposed to handle custom metric registry. Thanks

**Comment by ryantenney** [comment]
@Aloren do you have the getMetricRegistry method annotated `@Bean`? Evidently that was the problem @zkendall was having.
