### ISSUE TITLE
Option to prefix metric name with server name

### ISSUE THREAD

**Issue by philippe-tr** [ryantenney/metrics-spring#110]
I would like to incorporate the server name as a prefix to the metrics name. Maybe something like this:
```java
@Timed(name = "my.metric.name", absolute = true, prefixWithServerName = true)
public String myMethod() {
}
```
The library would use something like `Inet4Address.getLocalHost().getHostName()` to get the hostname dynamically and the published metric would then look like this: `myserver.my.metric.name`

Is there a way to do this now or would this need to be an enhancement?

**Comment by philippe-tr** [comment]
No comments?

**Comment by ryantenney** [comment]
The recommended approach for this would be to set the reporter's prefix instead of prefixing every metric.

**Comment by philippe-tr** [comment]
Yes! Even better. Thank you. I just wasn't aware of it. So I can do this:
````xml
<metrics:reporter type="graphite" metric-registry="metrics" host="carbon-host" port="2003" period="1s" prefix="this-server-name"/>
````
