### ISSUE TITLE
CSV Reporting support

### ISSUE THREAD

**Issue by fengapappit** [ryantenney/metrics-spring#121]
Hi,

I can't find anything about the CSV reporting support that metrics implements (https://dropwizard.github.io/metrics/3.1.0/manual/core/#man-core-reporters-csv).
Will there be a future CSV support for this plugin ?

**Comment by ryantenney** [comment]
Strange… I wonder why I didn't include that…

**Comment by ryantenney** [comment]
Fixed in 3.1.1
