### ISSUE TITLE
Example Java Config fails to register reporter for shutdown.

### ISSUE THREAD

**Issue by rripken** [ryantenney/metrics-spring#124]
I think the example @Configuration shown at http://www.ryantenney.com/metrics-spring/ should be changed to include a call to registerReporter.  

Especially if the example reporter starts a thread.  

Perhaps something like:

    @Configuration
    @EnableMetrics
    public class SpringConfiguringClass extends MetricsConfigurerAdapter {

       @Override
       public void configureReporters(MetricRegistry metricRegistry) {
           registerReporter(ConsoleReporter
               .forRegistry(metricRegistry)
               .build())
               .start(1, TimeUnit.MINUTES);
       }

**Comment by ryantenney** [comment]
Great suggestion, thanks!
