### ISSUE TITLE
InstrumentedFilter and Spring

### ISSUE THREAD

**Issue by markandirene** [ryantenney/metrics-spring#132]
Hello

A suggestion:

If I create a ContextListener that does not extend InstrumentedFilterContextListener then I can wire in the 'metrics' bean defined in:

	<metrics:metric-registry id="metrics" />

This gives me access to the InstrumentedFilter stats.

package com.mypackage

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import org.springframework.web.context.support.WebApplicationContextUtils;
import static com.codahale.metrics.servlet.InstrumentedFilter.REGISTRY_ATTRIBUTE;

public class EBIInstrumentedFilterContextListener implements
		ServletContextListener {

	@Override
	public void contextDestroyed(ServletContextEvent sce) {
	}

	@Override
	public void contextInitialized(ServletContextEvent sce) {
		sce.getServletContext().setAttribute(
				REGISTRY_ATTRIBUTE,
				WebApplicationContextUtils.getWebApplicationContext(
						sce.getServletContext()).getBean("metrics"));
	}
}

**Comment by ryantenney** [comment]
Could you please elaborate? I don't quite follow. Thanks!
