### ISSUE TITLE
Some problem with @Counted and @Gauge annotation

### ISSUE THREAD

**Issue by staleks** [ryantenney/metrics-spring#133]
Hi,

I'm in a process of evaluation of `metrics` 3rd party library for our next project.

Therefore I've assembled one small web application (WAR), based on Java, Spring and SpringMVC.
You can found project(code) on following URL: https://github.com/staleks/metrics

While JVM works fine, I'm troubling with @Counted and @Gauge annotations.
Here is the relevant part of Console log:

```
jvm.memory.total.max
             value = 2496135168
jvm.memory.total.used
             value = 246296672
jvm.thread-states.blocked.count
             value = 0
jvm.thread-states.count
             value = 14
jvm.thread-states.daemon.count
             value = 5
jvm.thread-states.deadlock.count
             value = 0
jvm.thread-states.deadlocks
             value = []
jvm.thread-states.new.count
             value = 0
jvm.thread-states.runnable.count
             value = 5
jvm.thread-states.terminated.count
             value = 0
jvm.thread-states.timed_waiting.count
             value = 6
jvm.thread-states.waiting.count
             value = 3
rs.in.staleksit.metrics.web.controller.IndexController.someProperty
             value = null

-- Counters --------------------------------------------------------------------
rs.in.staleksit.metrics.web.controller.IndexController.handle-counted
             count = 0

-- Timers ----------------------------------------------------------------------
rs.in.staleksit.metrics.web.controller.IndexController.handle-timed
             count = 13
         mean rate = 0.44 calls/second
     1-minute rate = 0.17 calls/second
     5-minute rate = 0.04 calls/second
    15-minute rate = 0.01 calls/second
               min = 0.00 milliseconds
               max = 18.53 milliseconds
              mean = 1.32 milliseconds
            stddev = 4.75 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 18.53 milliseconds
              98% <= 18.53 milliseconds
              99% <= 18.53 milliseconds
            99.9% <= 18.53 milliseconds

```

As you can see 

someProperty value is NULL, and handle-counted count is 0, while later @Timed part gives correct number of counts = 13.

Project is fully buildable, and runnable, so you can clone it to reproduce issue.

Thank You in advance for your help

**Comment by ryantenney** [comment]
Correct. @Counter defaults to counting the currently active method invocations, so the counter is incremented when the method is invoked, and decremented when the method returns. If you want it to count total invocations (increment on invocation, noop on return), you can set the attribute `@Counted(monotonic = true)`. Also I don't see any interactions with the someProperty field, and being an Integer and not an int, the null value of the gauge is correct.
