### ISSUE TITLE
Support NewRelic Reporter 

### ISSUE THREAD

**Issue by fgaule** [ryantenney/metrics-spring#134]
Hi falks, 

It would be cool to have NewRelic Reporter (https://github.com/palominolabs/metrics-new-relic) supported. What do you think?
In case you agree, I would be glad to make it happen.

Cheers

**Comment by ryantenney** [comment]
That would be awesome!

**Comment by fgaule** [comment]
Great. Should i fork from master? It has 3.1.1-SNAPSHOT pom version  when the last release is 3.1.2

**Comment by ryantenney** [comment]
Yea, I'll just also merge the change into the 3.1-maintenance branch.

**Comment by fgaule** [comment]
PR ready to be reviewed. :+1:

**Comment by ryantenney** [comment]
Thanks so much! I'm afraid I won't be able to get around to this for another week or so, but I promise I will soon :+1:
