### ISSUE TITLE
Reporter for influxdb?

### ISSUE THREAD

**Issue by davidkarlsen** [ryantenney/metrics-spring#139]
I´d like to try out influxdb.
How about adding a reporter configuration (parser&factory) for it using https://github.com/dropwizard/metrics/tree/master/metrics-influxdb ?
I can do an implementation if you want to?
Against master?

**Comment by ryantenney** [comment]
Check out the v4 branch of metrics as I've merged an influxdb client into
it, and if you want to take a shot at at a reporter element parser/bean
factory you should branch from the v4 branch of metrics-spring.

Thanks!

**Comment by davidkarlsen** [comment]
Fixed - so closing.
Can be tagged as milestone 4.0
