### ISSUE TITLE
@Counted seems not working correctly

### ISSUE THREAD

**Issue by bewang-tech** [ryantenney/metrics-spring#140]
I'm using `spring-boot-1.2.5-release`, Java Configuration,  metrics-jersey2, and metrics-sping
```
	compile "io.dropwizard.metrics:metrics-jersey2:3.1.2"
	compile "com.ryantenney.metrics:metrics-spring:3.1.2"
```
I also use JmxReporter.  When I add @Counted to a bean's method, I found the value does not increase, sometimes it was reset to zero. Sounds like there are multiple instances of the counter in different threads. But @Timed seems working correctly, the count of the timer metric increases.  

I don't think metrics-jersey2 will conflict with metrics-spring. I use the annotations for the jersey resources, and the metrics for jersey resources have different names.

I'm not sure where I did wrong.

**Comment by ryantenney** [comment]
The default behavior of @Counted is to only count active invocations of the method. Try setting the monotonic=true, and the counter will monotonically increase.

**Comment by bewang-tech** [comment]
Yes. I did not set monotonic=true. Thanks.
