### ISSUE TITLE
@Gauge and @CachedGauge annotation do not work properly on methods when using JavaConfig

### ISSUE THREAD

**Issue by segeon** [ryantenney/metrics-spring#141]
When I try to config metrics-spring using JavaConfig and add @Gauge and @CachedGauge annotation on methods, I can't get their metric info through jmx. Other annotations like @Counted, @Metered, @Timed work well. I looked into the source code, and find some problem that may be bugs.

In GaugeMethodAnnotationBeanPostProcessor line 28, the "return ReflectionUtils.invokeMethod(method, bean); " statement throw out java.lang.IllegalArgumentException: object is not an instance of declaring class. To my understanding, the argument bean is a proxy object, while method is the original Method object of the proxy target. We can't just call method like this. One simple solution is to find out the proxy object's corresponding Method and call it like this:

return ReflectionUtils.invokeMethod(bean.getClass().getMethod(method.getName(), method.parameterTypes), bean);

CachedGaugeAnnotationBeanPostProcessor class has the same problem and can be fixed in the same way.

**Comment by bwinant** [comment]
I am also encountering this exact issue. Would be great to see the pull request with the fix accepted

**Comment by ryantenney** [comment]
Tracking in #142
