### ISSUE TITLE
duplicate metrics getting registered when using with dropwizard

### ISSUE THREAD

**Issue by nikhilbhaware007** [ryantenney/metrics-spring#148]
Dropwizard only captures metrics over resource methods. I tried using metrics-spring library for enabling metrics over non resource methods.Now metrics over resource methods are incremented twice. Problem here is resource methods are being registered by dropwizard as well as metrics-spring.

**Comment by ryantenney** [comment]
Are you using Spring's @ComponentScan or `<context:component-scan>`?

**Comment by nikhilbhaware007** [comment]
yes.I am using @ComponentScan.

**Comment by nikhilbhaware007** [comment]
still facing same issue!!

**Comment by nikhilbhaware007** [comment]
what difference does it make using @componantScan ??

**Comment by ryantenney** [comment]
My mistake, I missed that you're using Dropwizard in conjunction with Spring. Metrics-spring operates on all beans within the Spring context, so I think the only way to fix this would be to move your Dropwizard resource classes to a Spring subcontext.

**Comment by souvikmitra** [comment]
Hey @ryantenney, do you think that having an option of specifying a custom matcher for excluding certain classes (resources in this case) will be a better solution ? Something similar to what metrics-guice has. (https://github.com/palominolabs/metrics-guice/pull/5)

**Comment by ryantenney** [comment]
I'd be open to including this feature, though I don't know when I'd be able to get around to implementing it.

**Comment by souvikmitra** [comment]
@nikhilbhaware007 and I will be happy to help with the code. :)
