### ISSUE TITLE
Allow custom reservoir for Timer

### ISSUE THREAD

**Issue by apolci** [ryantenney/metrics-spring#149]
Currently I don't see any way to customized the reservoir of the timer created by a Timed annotation.
 
In my use case I need to customize both the default reservoir and the reservoir used for specific methods.
 
The fact that most of the classes have package visibility makes difficult also to extend/reuse them, for example to create a custom annotation for a Timer with customized Reservoir.

**Comment by ryantenney** [comment]
Tracking in #150
