### ISSUE TITLE
@Gauge reference alters me.

### ISSUE THREAD

**Issue by Gauge** [ryantenney/metrics-spring#158]
Hi there, I see your project is coming along nicely. Just wanted to let you know that using the @ symbol is a reference to github users. I currently get contacted via email every time @Gauge is used. Its not a big deal to me but i thought id let you know.

Good luck in current and future projects,
Gauge

**Comment by ryantenney** [comment]
I'm very sorry about that! It may be possible to block/ignore this project so you don't get any notifications. I've tried to avoid tagging you, but I can't prevent others from doing so. Thanks for being so understanding!
