### ISSUE TITLE
ES reporter parser

### ISSUE THREAD

**Issue by davidkarlsen** [ryantenney/metrics-spring#167]
Seems like ES is gaining momentum in the time-series world:
https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store
http://cds.cern.ch/record/2011172/files/LHCb-TALK-2015-060.pdf

A metrics api reporter already exists in:
https://github.com/elastic/elasticsearch-metrics-reporter-java

If I made a pull request for spring bean definition parser - would you care to merge it into springmetrics?

**Comment by ryantenney** [comment]
Absolutely!

**Comment by kossmoboleat** [comment]
I would like to use the es-reporter with metrics, can this commit be merged?

UPDATE: oh I've seen you already merged it, sorry.

**Comment by davidkarlsen** [comment]
Could you do a release as well?

**Comment by davidkarlsen** [comment]
@ryantenney ping? how about a relase?

**Comment by ryantenney** [comment]
Let me review the open tickets and see if there's anything else that needs to be released, and I'll get back to you soon.

**Comment by davidkarlsen** [comment]
@ryantenney ping?
Better to release often and small than seldom.
