### ISSUE TITLE
Why use this library when Drop wizard has spring integration?

### ISSUE THREAD

**Issue by smojtabai** [ryantenney/metrics-spring#171]
I am trying to figure out the difference between this library and this:

https://dropwizard.github.io/metrics/2.2.0/manual/spring/

Any thoughts?

**Comment by ryantenney** [comment]
It's the same thing, I originally contributed this library to Metrics for version 2.2.0, and it was later removed and I continued maintaining it in this repository. Version 2.2.0 is now about 4 years old. Version 3.1.2 is current.

**Comment by smojtabai** [comment]
thanks for quick response!
