### ISSUE TITLE
get the 2 identical interceptorsAndDynamicMethodMatchers for @Timed 

### ISSUE THREAD

**Issue by weizhu-us** [ryantenney/metrics-spring#180]
I am using Spring 4.2.5, Jersey 2.22.2, Tomcat 8.0

I am using @Timed annotation and found that for the method invocation, there are two TimedMethodInterceptor in the interceptorsAndDynamicMethodMatchers. It ends up the count doubles the real method invocation.

If I run the same webapp using Jetty Runner in Intellij IDEA, I don't see the problem. Any clue?

Thanks.

**Comment by weizhu-us** [comment]
Just debugged a bit, there are two BeanPostProcessors with Timed annotations.
<img width="1118" alt="beanposprocessors" src="https://cloud.githubusercontent.com/assets/3794351/14749531/c12e796e-0874-11e6-98cc-423f8bdcc04c.png">

**Comment by ryantenney** [comment]
The only possibility I can think of is that you have two `<metrics:annotation-driven />` xml elements in your Spring context.

**Comment by weizhu-us** [comment]
That is the first thing I checked. Only one <metrics:annotation-driven />. The odd thing is that it only happens when I deploy the war to Tomcat. If I use Intellij embedded Jetty runner, I don't see the problem.

**Comment by weizhu-us** [comment]
I finally figured out what caused it. Tomcat unpack the war file and create directory in both Catalinahome/webapps and Catalinahome/work directory which somehow caused the issue. If I set unpackWARs attribute set to "false", the issue is gone.

**Comment by ryantenney** [comment]
I've done that before! Glad to hear it!
