### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by baynezy** [ryantenney/metrics-spring#204]
Good morning.
Has this project been abandoned?

- I could not find any commits from this year
- No response on issues or PRs from project owner (@ryantenney) since March

I am looking to utilise it in something I am doing, but don't want to progress if it is not being maintained anymore.

**Comment by ryantenney** [comment]
Good morning!  The project is not abandoned, however it also isn't under active development.  at this point I don't think there are any new features I want to add to it, and there don't appear to be any critical issues that are preventing people from using it (there is one issue with Spring Boot that has been reported by a couple people, but so far I have not been able to reproduce it).

**Comment by baynezy** [comment]
Thanks @ryantenney
