### ISSUE TITLE
Register metric for a method at runtime

### ISSUE THREAD

**Issue by olayinkasf** [ryantenney/metrics-spring#205]
I am initializing a bean dynamically and I would like to know how to register one of the methods to the registry. 

I know I can simply annotate the class but I have multiple instances and I would prefer to have different names  for each metric.

**Comment by jmlucjav** [comment]
I am in a similar scenario. I create the beans dynamically, and register them with Boot with:

`            configurableBeanFactory.registerSingleton(name, bean);`

But of course, @Timed annotations in that bean's methods are not taken into account. Would be supper handy finding a way to hook them with metrics too.
