### ISSUE TITLE
Minnor typos in Readme

### ISSUE THREAD

**Issue by abelsromero** [ryantenney/metrics-spring#210]
I've noticed many ocurrences of the term `Regsitry` in the README. Really, just a silly thing that makes me smile, but it'd wouldn't take much effort to fix.

Btw, may I sugggest migrating to Asciidoctor? :P

**Comment by ryantenney** [comment]
Fixed in f41db8a2b201f1400631b3256d2c7c3df3d8d3c1. Thanks for bringing it to my attention, now excuse me while I go hang my head in shame.

**Comment by ryantenney** [comment]
I have no experience with Asciidoctor, why do you suggest it?

**Comment by abelsromero** [comment]
> I have no experience with Asciidoctor, why do you suggest it?

Overall is a more mature tool to write documentation, it has all that Markdown has and much more (eg. admonitions). It is supported by GitHub, so the README will still be visible as it is now. It is widely known in Java environments and afaik is the defacto tool for official Spring documentation also.
The only problem I see us integrating it with the current site you have, but other than that I see no reason to migrate, I can do a fork with a demo.

**Comment by abelsromero** [comment]
Here you can see the result: https://github.com/abelsromero/metrics-spring/blob/change_docs_to_AsciiDoc/README.adoc

You will see the differences are not much and the renderd HTML is almost the same.
The only relevant changes are:
* Introduced `release-version` replacements (aka. variable) for better manteinability
* Added autogenerated table of contents: this is optional, but I like to add it to make browsing easier and see the global structure while writting.
* Added link to Maven badge

If you like the change, I've been thinking of other things that would make the docs clearer imho.
* Use of include instead of link for Shade doc
* Use labeled lists to highlight config params like here (https://github.com/asciidoctor/asciidoctor-maven-plugin#configuration), or just a table.
* Define replacements for common config descriptions
* Adding more details in the examples with callouts (http://asciidoctor.org/docs/user-manual/#callouts)
