### ISSUE TITLE
please upgrade metrics to 4.0.0

### ISSUE THREAD

**Issue by Anricx** [ryantenney/metrics-spring#211]
please upgrade metrics to 4.0.0

**Comment by jiri-pejchal** [comment]
There has been some package changes e.g. 
``com.codahale.metrics.JmxReporter`` -> ``com.codahale.metrics.jmx.JmxReporter``

**Comment by Anricx** [comment]
it seems metrics 4.x is not stable for now, fall back to 3.x, but why not just merge this resp. with metrics?
