### ISSUE TITLE
Using multiple metrics annotations on a single target method

### ISSUE THREAD

**Issue by MartinAhrer** [ryantenney/metrics-spring#52]
Tried to put more than one metrics annotation which fails with an exception:
"name  is already used for a different type of metric"

``` java
    // Only one annotation allowed at a time???
    //@Counted
    @Timed
    @RequestMapping(method = RequestMethod.GET)
    public ResponseEntity<TaskResource> showAll() {
        //TODO use repository for fetching data
        TaskResource taskResource = taskResourceAssembler.toResource(new Task(1l, "task"));
        return new ResponseEntity<>(taskResource, HttpStatus.OK);
    }
```

Any specific technical limitation why this is not possible? Does it mean that in such a case the name has to be set explicitely?

**Comment by cakraww** [comment]
`@Timed` already covers `@Count` and `@Metered` doesn't it? Putting `@Metered` alongside with `@Timed` is redundant, I think.
