### ISSUE TITLE
Health check registration support

### ISSUE THREAD

**Issue by adenysenko** [ryantenney/metrics-spring#76]
It would be nice if we can register health checks via spring configuration:
```
<metrics:register metric-registry="metrics">
    <bean metrics:name="database" class="DatabaseHealthCheck"/>..</bean>
</metrics>
```

which is equal to:

```
registry.register("database", new DatabaseHealthCheck(database));
```

**Comment by ryantenney** [comment]
Great note about being able to use @Component to name the health check. Maybe not a perfect solution, but it works. Would consider some other mechanism to register/name healthchecks in future versions if there is demand for it.
