### ISSUE TITLE
Metrics 3.1.0 Release

### ISSUE THREAD

**Issue by cemo** [ryantenney/metrics-spring#91]
@ryantenney, 

Is it possible to cut a release with latest Metrics version?

**Comment by ArekCzarnik** [comment]
After excluding dependencies:
<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-annotation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-healthchecks</artifactId>
				</exclusion>
i become:

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.ryantenney.metrics.spring.ExceptionMeteredMethodInterceptor
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)

**Comment by cooniur** [comment]
@ArekCzarnik 
I excludes the following artifacts but run smoothly.

		<dependency>
			<groupId>com.ryantenney.metrics</groupId>
			<artifactId>metrics-spring</artifactId>
			<version>3.0.4</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-healthchecks</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-annotation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-jvm</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-servlets</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-ganglia</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.codahale.metrics</groupId>
					<artifactId>metrics-graphite</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by Alexandra12** [comment]
When can we expect the release ? I would really need the graphite-pickle reporter ..

**Comment by ryantenney** [comment]
I just pushed the 3.1.2 release to Maven Central

**Comment by cooniur** [comment]
@ryantenney Thanks for the hard work!

**Comment by Alexandra12** [comment]
Maybe it's just me, but I'm not able to find it.

**Comment by geissbock** [comment]
@Alexandra12 Same here. I can't find it in Maven Central, and the pom.xml in the master still states 3.1.0-SNAPSHOT as the version, and I don't find any commit (let alone tag or branch) with the version 3.1.2.

@ryantenney Did you maybe forget to push something? ;-)

**Comment by ryantenney** [comment]
My bad, I inadvertently commented on this, when in fact I was releasing metrics 3.1.2.  I have been holding up the release up on a bug that I just can't seem to fix.

**Comment by Alexandra12** [comment]
@ryantenney  So, just to be clear, is there a release which includes the graphite reporters with transport property ? If not, when can we expect one ? Sorry for insisting on this. 

Thanks, 
Ale

**Comment by ryantenney** [comment]
Since I don't have line of sight on fixing the bug, I'll prioritize getting a 3.1.0 release out with that feature. Expect something within a few days, and feel free to harass me if I don't meet that goal.

**Comment by Alexandra12** [comment]
Thanks :)

**Comment by ryantenney** [comment]
@Alexandra12 I just pushed 3.1.0-SNAPSHOT to Sonatype's snapshot repository. Care to check it out and see if it does what you need?

**Comment by Alexandra12** [comment]
Hei, just checked it and it's working. Please push the release version when you get to it. Thanks a lot for unblocking me.

**Comment by davidkarlsen** [comment]
This issue can be closed as its now avail at:
http://repo1.maven.org/maven2/com/ryantenney/metrics/metrics-spring/3.1.0/
