### ISSUE TITLE
Without MVC

### ISSUE THREAD

**Issue by s17t** [ryantenney/metrics-spring#99]
Hi, I have a backend application built on top of Spring using its IoC and its context with autowiring. I tried to use metrics-spring but the given annotations simple don't work while plain simple metrics work.

Edit: the annotations are simple ignored.

Are there specific reason why metrincs-springs doesn't working ?

I'm using spring 3.0.x

Thank you

**Comment by ryantenney** [comment]
I'm trying to fix that issue. I'm going to close this and continue to track it in #90.
